name: Run unit tests
on:
  workflow_call:
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  wait-for-browserstack:
    name: Wait for other test runs
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          while  curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" \
            -X GET "https://api-cloud.browserstack.com/automate/plan.json" 2> /dev/null \
             | jq -e '.queued_sessions > 0' > /dev/null; do
            delay=$(( 60 + $(shuf -i 1-60 -n 1) ))
            echo "Other browserstack sessions are currently queued, checking again in ${delay}s"
            sleep $delay
          done
