name: Run unit tests
on:
  workflow_call:
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  wait-for-browserstack:
    name: Wait for browserstack sessions
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          while            
            status=$(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" \
              -X GET "https://api-cloud.browserstack.com/automate/plan.json" 2> /dev/null);
            running=$(jq '.parallel_sessions_running' <<< $status)
            max_running=$(jq '.parallel_sessions_max_allowed' <<< $status)
            queued=$(jq '.queued_sessions' <<< $status)
            max_queued=$(jq '.queued_sessions_max_allowed' <<< $status)
            spare=$(( ${max_running} + ${max_queued} - ${running} - ${queued} ))
            required=6
            echo "Browserstack status: ${running} sessions running, ${queued} queued, ${spare} free"
            (( ${required} > ${spare} ))
          do
            delay=$(( 60 + $(shuf -i 1-60 -n 1) ))
            echo "Waiting for ${required} sessions to free up, checking again in ${delay}s"
            sleep $delay
          done
