name: Run tests
on:
  workflow_call:
    inputs:
      description:
        required: true
        type: string
      cmd:
        required: true
        type: string
    outputs:
      out:
        description: "Cache key for the working directory after running tests"
        value: ${{ jobs.final-chunk.outputs.out }}
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  test-chunk-1:
    id: chunk-1
    name: Run tests (${{ inputs.description }}, chunk 1 of 4)
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 1
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  test-chunk-2:
    id: chunk-2
    name: Run tests ($ {{ inputs.description }}, chunk 2 of 4)
    needs: test-chunk-1
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 2
      wdir: ${{ jobs.chunk-1.outputs.out }}
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  test-chunk-3:
    id: chunk-3
    name: Run tests ($ {{ inputs.description }}, chunk 3 of 4)
    needs: test-chunk-2
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 3
      wdir: ${{ jobs.chunk-2.outputs.out }}
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  test-chunk-4:
    id: final-chunk
    name: Run tests ($ {{ inputs.description }}, chunk 4 of 4)
    needs: test-chunk-3
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 4
      wdir: ${{ jobs.chunk-3.outputs.out }}
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
