name: Run tests
on:
  workflow_call:
    inputs:
      description:
        required: true
        type: string
      cmd:
        required: true
        type: string
    outputs:
      wdir:
        description: "Cache key for the working directory after running tests"
        value: ${{ jobs.chunk-4.outputs.wdir }}
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  chunk-1:
    name: Run tests (${{ inputs.description }}, chunk 1 of 4)
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 1
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  chunk-2:
    name: Run tests (${{ inputs.description }}, chunk 2 of 4)
    needs: chunk-1
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 2
      wdir: ${{ needs.chunk-1.outputs.wdir }}
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  chunk-3:
    name: Run tests (${{ inputs.description }}, chunk 3 of 4)
    needs: chunk-2
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 3
      wdir: ${{ needs.chunk-2.outputs.wdir }}
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  chunk-4:
    name: Run tests (${{ inputs.description }}, chunk 4 of 4)
    needs: chunk-3
    uses: ./.github/workflows/test-chunk.yml
    with:
      chunk-no: 4
      wdir: ${{ needs.chunk-3.outputs.wdir }}
      cmd: ${{ inputs.cmd }}
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
