name: Run tests

on:
  push:
    branches:
      - master
      - '*-legacy'
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    name: "Check out source and install dependencies"
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout code (PR)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout code (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Cache source
        uses: actions/cache/save@v4
        with:
          path: .
          key: source-${{ github.run_id }}

  lint:
    name: "Run linter"
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Restore source
        uses: actions/cache/restore@v4
        with:
          path: .
          key: source-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: lint
        run: npx eslint
      
  test-no-features:
    if: false
    name: "Unit tests (all features disabled)"
    needs: checkout
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      build-cmd: npx gulp precompile-all-features-disabled
      test-cmd: npx gulp test-all-features-disabled-nobuild
      serialize: false
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  test:
    name: "Unit tests (all features enabled + coverage)"
    needs: checkout
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      build-cmd: npx gulp precompile
      test-cmd: npx gulp test-only-nobuild
      serialize: true
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  test-e2e:
    if: false
    name: "End-to-end tests"
    needs: checkout
    runs-on: ubuntu-latest
    concurrency:
      # see test-chunk.yml for notes on concurrency groups
      group: browserstack-${{ github.run_id }}
      cancel-in-progress: false
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Restore source
        uses: actions/cache/restore@v4
        with:
          path: .
          key: source-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npx gulp e2e-test

  coveralls:
    name: Update coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Restore working directory
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ needs.test.outputs.wdir }}
          fail-on-cache-miss: true
      - name: Coveralls (push)
        if: ${{ github.event_name == 'push' }}
        uses: coverallsapp/github-action@v2
        with:
          git-branch: ${{ github.ref }}
          git-commit: ${{ github.sha }}
          compare-ref: ${{ github.ref }}
          compare-sha: ${{ github.event.push.before }}
      - name: Coveralls (PR)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: coverallsapp/github-action@v2
        with:
          git-branch: ${{ github.event.pull_request.head.ref }}
          git-commit: ${{ github.event.pull_request.head.sha }}
          compare-ref: ${{ github.event.pull_request.base.ref }}
          compare-sha: ${{ github.event.pull_request.base.sha }}
