name: Run tests

on:
  push:
    branches:
      - master
      - '*-legacy'
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    name: "Check out source and install dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Cache source
        uses: actions/cache/save@v4
        with:
          path: .
          key: source-${{ github.sha }}

  test:
    name: "Run tests (all features enabled + coverage)"
    needs: build
    uses: ./.github/workflows/run-tests.yml
    with:
      description: all features enabled + coverage
      build-cmd: npx gulp precompile
      test-cmd: npx gulp test-pipeline --browserstack
    secrets:
      BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

  coveralls:
    name: Update coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Restore working directory
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ needs.test.outputs.wdir }}
      - name: Coveralls
        uses: coverallsapp/github-action@v2
