name: Run tests
on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string
      chunk-no:
        required: true
        type: number
      wdir:
        required: false
        type: string
    outputs:
      out:
        description: "Cache key for the working directory after running tests"
        value: test-${{ inputs.cmd }}-${{ inputs.chunk-no }}-${{ github.sha }}
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

concurrency:
  group: 'browserstack'
  cancel-in-progress: false

jobs:
  test:
    name: "Test chunk ${{ inputs.chunk-no }}"
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      TEST_CHUNKS: 4
      TEST_CHUNK: ${{ inputs.chunk-no }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore working directory
        if: ${{ inputs.wdir != null }}
        id: restore-dir
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ inputs.wdir }}

      - name: Fetch build output from cache
        if: ${{ inputs.wdir == null }}
        uses: actions/cache/restore@v4
        with:
          path: .
          key: build-${{ github.sha }}

      - name: Run tests
        run: ${{ inputs.cmd }}

      - name: Save working directory
        uses: actions/cache/save@v4
        with:
          path: .
          key: test-${{ inputs.cmd }}-${{ inputs.chunk-no }}-${{ github.sha }}

