name: Run tests
on:
  workflow_call:
    inputs:
      chunk-no:
        required: true
        type: number
      bs-username:
        required: true
        type: string
      bs-key:
        required: true
        type: string

jobs:
  test:
    name: "Test chunk ${{ inputs.chunk-no }}"
    env:
      BROWSERSTACK_USERNAME: ${{ inputs.bs-username }}
      BROWSERSTACK_ACCESS_KEY: ${{ inputs.bs-key }}
      TEST_CHUNKS: 4
      TEST_CHUNK: ${{ inputs.chunk-no }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch build output from cache
        uses: actions/cache/restore@v4
        with:
          path: .
          key: build-${{ github.sha }}

      - name: Restore coverage cache
        uses: actions/cache/restore@v4
        with:
          path: _coverage
          key: coverage-${{ github.sha }}

      - name: Run tests
        run: npx gulp test-pipeline --browserstack

      - name: Move coverage result
        run: >
          mkdir -p _coverage
          mv -r build/coverage/* _coverage/

      - name: Cache coverage result
        uses: actions/cache/save@v4
        with:
          path: _coverage
          key: coverage-${{ github.sha }}

